# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata: { type: attribute }
    mappings:
        media:
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            uri_prefix: /uploads/media
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  
